version: "3.7"

networks:
  padrao:
    driver: bridge

services:
  redis:
    image: redis
    networks:
      - padrao
    ports:
      - "6379:6379"

  websocket2:
    image: websocket
    container_name: detoka
    command: ./main
    environment:
      - APPID=2222
    depends_on:
      - redis
    networks:
      - padrao

  websocket1:
    build: .
    image: websocket
    container_name: meu_piru
    command: ./main
    environment:
      - APPID=1111
    depends_on:
      - redis
    networks:
      - padrao

  loadbalancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - padrao
    depends_on:
      - websocket1
      - websocket2
